name: Python 3.14 (free-threaded)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.14 (free-threaded)
      uses: actions/setup-python@v4
      with:
        python-version: '3.14'
        architecture: 'x64-freethreaded'
    - name: Set PYTHON_GIL
      shell: bash
      run: echo "PYTHON_GIL=0" >> "$GITHUB_ENV"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,examples]
    - name: Run tests
      shell: bash
      run: |
        ./run_tests_and_log.sh
