name: Release Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-3-6:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.6
      uses: actions/setup-python@v4
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,examples]
    - name: Run tests
      run: |
        ./run_tests_and_log.sh
  test-3-7:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,examples]
    - name: Run tests
      run: |
        ./run_tests_and_log.sh
  test-3-8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,examples]
    - name: Run tests
      run: |
        ./run_tests_and_log.sh
  test-3-9:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,examples]
    - name: Run tests
      run: |
        ./run_tests_and_log.sh
  test-3-10:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,examples]
    - name: Run tests
      run: |
        ./run_tests_and_log.sh
  test-3-11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,examples]
    - name: Run tests
      run: |
        ./run_tests_and_log.sh
  test-3-12:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,examples]
    - name: Run tests
      run: |
        ./run_tests_and_log.sh
  test-3-13:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,examples]
    - name: Run tests
      run: |
        ./run_tests_and_log.sh
  test-3-14:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.14
      uses: actions/setup-python@v4
      with:
        python-version: '3.14'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,examples]
    - name: Run tests
      run: |
        ./run_tests_and_log.sh
  test-3-14-freethreaded:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.14 (free-threaded)
      uses: actions/setup-python@v4
      with:
        python-version: '3.14t'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,examples]
    - name: Run tests
      run: |
        ./run_tests_and_log.sh
