name: Release Testing

on: [push, pull_request, workflow_dispatch]

jobs:
  test-3-6:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.6
      uses: actions/setup-python@v4
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,examples]
    - name: Run tests
      shell: bash
      run: |
        ./run_tests_and_log.sh
  test-3-7:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,examples]
    - name: Run tests
      shell: bash
      run: |
        ./run_tests_and_log.sh
  test-3-8:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,examples]
    - name: Run tests
      shell: bash
      run: |
        ./run_tests_and_log.sh
  test-3-9:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,examples]
    - name: Run tests
      shell: bash
      run: |
        ./run_tests_and_log.sh
  test-3-10:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,examples]
    - name: Run tests
      shell: bash
      run: |
        ./run_tests_and_log.sh
  test-3-11:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,examples]
    - name: Run tests
      shell: bash
      run: |
        ./run_tests_and_log.sh
  test-3-12:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,examples]
    - name: Run tests
      shell: bash
      run: |
        ./run_tests_and_log.sh
  test-3-13:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,examples]
    - name: Run tests
      shell: bash
      run: |
        ./run_tests_and_log.sh
  test-3-14:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.14
      uses: actions/setup-python@v4
      with:
        python-version: '3.14'
        allow-prereleases: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,examples]
    - name: Run tests
      shell: bash
      run: |
        ./run_tests_and_log.sh
  test-3-14t:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.14 (free-threaded)
      uses: actions/setup-python@v4
      with:
        python-version: '3.14'
        architecture: 'x64-freethreaded'
    - name: Set PYTHON_GIL
      shell: bash
      run: echo "PYTHON_GIL=0" >> "$GITHUB_ENV"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,examples]
    - name: Run tests
      shell: bash
      run: |
        ./run_tests_and_log.sh
